# Generated by Django 2.0.2 on 2020-07-23 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_module', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Marks_ClassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=15)),
                ('Term', models.CharField(max_length=10)),
                ('Maximum_Marks', models.IntegerField()),
                ('Marks', models.IntegerField()),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_module.Student_General_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Marks_FA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=10)),
                ('Term', models.CharField(max_length=5)),
                ('Maximum_Marks', models.IntegerField()),
                ('Marks', models.IntegerField()),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_module.Student_General_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Marks_SA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=15)),
                ('Term', models.CharField(max_length=5)),
                ('Maximum_Marks', models.IntegerField()),
                ('Marks', models.IntegerField()),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_module.Student_General_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('Subject', models.CharField(max_length=15)),
                ('Notes', models.FileField(upload_to='Notes')),
                ('Description', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Subject', models.CharField(max_length=15)),
                ('Syllabus', models.CharField(max_length=100)),
                ('Term', models.CharField(max_length=5)),
                ('File', models.FileField(blank=True, upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Academy_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Teacher_Class', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Class_Teacher_Section', models.CharField(blank=True, max_length=1)),
                ('Subject', models.CharField(blank=True, max_length=15)),
                ('Class', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Section', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audibility_Sum', models.IntegerField()),
                ('Knowledge_Sum', models.IntegerField()),
                ('Explaination_Sum', models.IntegerField()),
                ('Doubt_Clearance_Sum', models.IntegerField()),
                ('Count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_General_Info',
            fields=[
                ('Teacher_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Teacher_Phone_Number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be correct Add 0 at starting', regex='^(0)+\\d{10}$')])),
                ('Address', models.TextField(max_length=50)),
                ('Qualification', models.CharField(max_length=10)),
                ('Photo', models.ImageField(blank=True, default='Photo/default.jpg', upload_to='photo')),
            ],
        ),
        migrations.AddField(
            model_name='teacher_feedback',
            name='Teacher_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_module.Teacher_General_Info'),
        ),
        migrations.AddField(
            model_name='teacher_academy_info',
            name='teacher_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_module.Teacher_General_Info'),
        ),
        migrations.AddField(
            model_name='student_notes',
            name='Teacher_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_module.Teacher_General_Info'),
        ),
    ]
