# Generated by Django 2.0.2 on 2020-07-26 17:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_module', '0001_initial'),
        ('Teacher_module', '0002_auto_20200723_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=50)),
                ('Question_Paper', models.FileField(upload_to='Question')),
                ('Class', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('Subject', models.CharField(max_length=15)),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_module.Teacher_General_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('Assignment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_module.Assignment')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_module.Student_General_Info')),
            ],
        ),
    ]
