# Generated by Django 2.0.2 on 2020-07-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_module', '0003_assignment_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_submission',
            name='Student_Name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
